### ポジションを全部日本円に変えるノートブック

成り行き注文で全てのポジションを日本円に変える．   
実行間隔が短すぎて処理ができないことがあるので，その場合は再度実行するかsleepを挟む．

In [1]:
import sys
sys.path.append('../')
import os

In [2]:
import json
import pandas as pd

#自作モジュール
from gmo_api import GmoApi_private

In [3]:
# config.jsonの読み込み
with open("../config.json", 'r') as f:
    config = json.load(f)

apiKey    = config['GMO_API_KEY']
secretKey = config['GMO_API_SECRET']
symbols = config['symbols']

gmo_api_private = GmoApi_private(apiKey, secretKey)

BASE_DIR = '../data/historical_klines/'

In [4]:
position_df = pd.DataFrame(gmo_api_private.get_balance()['data'])
position_df[['amount', 'available', 'conversionRate']] = position_df[['amount', 'available', 'conversionRate']].astype(float)
position_df

        amount   available  conversionRate symbol
0   119893.000  119893.000    1.000000e+00    JPY
1        0.000       0.000    4.023108e+06    BTC
2        0.000       0.000    2.532150e+05    ETH
3        0.000       0.000    3.133700e+04    BCH
4        0.000       0.000    1.152500e+04    LTC
5        0.000       0.000    8.759900e+01    XRP
6        0.000       0.000    4.222000e+00    XEM
7       18.000      18.000    1.941700e+01    XLM
8        0.000       0.000    2.833600e+01    BAT
9        0.000       0.000    7.785657e+01    OMG
10       0.000       0.000    1.104820e+02    XTZ
11       0.000       0.000    3.503360e+02   QTUM
12       0.000       0.000    3.928600e+01    ENJ
13       0.000       0.000    6.810000e+02    DOT
14       0.000       0.000    1.150000e+03   ATOM
15       0.015       0.015    1.694050e+05    MKR
16       0.000       0.000    1.418000e+02    DAI
17       0.000       0.000    4.036000e+00    XYM
18       0.000       0.000    6.623000e+01   MONA
19       0.000       0.000    2.970000e-01    FCR
20       0.000       0.000    3.969700e+01    ADA
21       0.000       0.000    9.740000e+02   LINK
22       0.000       0.000    1.014500e+01   DOGE
23       0.000       0.000    3.039000e+03    SOL
24       0.000       0.000    2.037260e+00    FLR
25       0.000       0.000    7.029000e+00   ASTR
26       0.000       0.000    5.649700e+02    FIL
27       0.000       0.000    5.624700e+01   SAND
28       0.000       0.000    1.045200e+01    CHZ

In [5]:
for symbol in symbols:
    size = position_df.loc[position_df['symbol'] == symbol]['amount'].values[0]
    gmo_api_private.post_order(symbol = symbol, side = 'SELL', executionType = 'MARKET', size = size)